# CONFIGURATION UNIQUE pour RENDER - Pas de profils, pas d'options
spring:
 config:
  activate:
   on-profile: nosec
datasource:
    # URL ABSOLUE vers votre base Render - Ã€ ADAPTER !
    url: jdbc:postgresql://dpg-d5icgnh4tr6s73a3v640-a.oregon-postgres.render.com:5432/recruitment_db
    username: postgres
    password: mohamed 
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: -1
  
  jpa:
    hibernate:
      ddl-auto: valide
    show-sql: false
    
  security:
    basic:
      enabled: false
 spring:
  config:
    activate:
      on-profile: production
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/recruitment_db}
  jpa:
    hibernate:
      ddl-auto: validate
