services:
  - type: web
    name: sigc
    env: docker
    rootDir: sigc2/sigc
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    healthCheckPath: /health
    initialDelay: 180
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
